Vagrant.require_version ">= 1.6.2"

$set_environment_variables = <<ENV_VARS_SCRIPT
gpg_pub_key_file="/tmp/gpg_pub.key"
rm -f $gpg_pub_key_file
echo "#{ENV['GPG_PUB_KEY']}" > $gpg_pub_key_file

tee /etc/profile.d/set_build_env.sh > /dev/null <<EOF
export AWS_ACCESS_KEY_ID=#{ENV['AWS_ACCESS_KEY_ID']}
export AWS_DEFAULT_REGION=#{ENV['AWS_DEFAULT_REGION']}
export SOURCE_BRANCH=#{ENV['SOURCE_BRANCH']}
export REPO_PATH=#{ENV['REPO_PATH']}
export PKG_TYPE=#{ENV['PKG_TYPE']}
export DIST_NAME=#{ENV['DIST_NAME']}
export DIST_VER=#{ENV['DIST_VER']}
export GITHUB_EVENT_NAME=#{ENV['GITHUB_EVENT_NAME']}
export GITHUB_RUN_NUMBER=#{ENV['GITHUB_RUN_NUMBER']}

cd /home/elastio/elastio-snap
EOF

chmod +x /etc/profile.d/set_build_env.sh
ENV_VARS_SCRIPT

DISTROS = [ "debian8", "debian9", "debian10", "amazon2", "centos6", "centos7", "centos8", "fedora31", "fedora32" ]

Vagrant.configure("2") do |config|

  DISTROS.each do |distro|
    box = "#{distro}-amd64-build"
    config.vm.define "#{box}-#{ENV['RUNNER_NUM']}", autostart: false do |b|
      b.vm.box = "#{box}"
      b.vm.box_url = [ "https://s3.eu-central-1.wasabisys.com/blobs-wasabi.elastio.dev/devboxes/master/#{box}/#{box}.box" ]
    end
  end

  config.vm.provision "shell", inline: $set_environment_variables, run: "always"
  config.vm.synced_folder "../../", "/home/elastio/elastio-snap", type: "rsync",
    rsync__args: ["-rLkz", "--delete", "--filter=:- .gitignore"], rsync__exclude: [".vagrant/"]
end
