.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UPDATE\-IMG" "8" "March 2016" "Datto Inc" ""
.
.SH "NAME"
\fBupdate\-img\fR
.
.SH "NAME"
update\-img \- Update a backup image with elastio-snap COW file\.
.
.SH "SYNOPSIS"
\fBupdate\-img <snapshot device> <cow file> <image file>\fR
.
.SH "DESCRIPTION"
\fBupdate\-img\fR is a simple tool to efficiently update backup images made by the elastio-snap kernel module\. It uses the leftover COW file from elastio-snap\'s incremental state to efficiently update an existing backup image\. See the man page on \fBelioctl\fR for an example use case\.
.
.SS "EXAMPLES"
\fB# update\-img /dev/elastio-snap4 /var/backup/elastio1 /mnt/data/backup\-img\fR
.
.P
This command will update a previously backed up snapshot \fB/mnt/data/backup\-img\fR with the changed blocks indicated by \fB/var/backup/elastio1\fR from \fB/dev/elastio-snap4\fR\.
.
.P
NOTE: \fB<snapshot device>\fR MUST be the NEXT snapshot after the one that \fB<image file>\fR was copied from\.
.
.SH "Bugs"
.
.SH "Author"
.
.nf

Tom Caputi (tcaputi@datto\.com)
.
.fi

