Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    config.vm.define "fedora32-amd64-build"
    config.vm.box = "fedora32-amd64-build"
    config.vm.box_url = [ "https://s3.eu-central-1.wasabisys.com/blobs-wasabi.elastio.dev/devboxes/master/fedora32-amd64-build/fedora32-amd64-build.box" ]

    $set_environment_variables = <<ENV_VARS_SCRIPT
      tee /etc/profile.d/set_build_env.sh > /dev/null <<EOF
export AWS_ACCESS_KEY_ID=#{ENV['AWS_ACCESS_KEY_ID']}
export AWS_DEFAULT_REGION=#{ENV['AWS_DEFAULT_REGION']}
export SOURCE_BRANCH=#{ENV['SOURCE_BRANCH']}
export REPO_PATH=#{ENV['REPO_PATH']}
export PKG_TYPE=#{ENV['PKG_TYPE']}
export DIST_NAME=#{ENV['DIST_NAME']}
export DIST_VER=#{ENV['DIST_VER']}
export GITHUB_EVENT_NAME=#{ENV['GITHUB_EVENT_NAME']}
export GITHUB_RUN_NUMBER=#{ENV['GITHUB_RUN_NUMBER']}
EOF
      chmod +x /etc/profile.d/set_build_env.sh
ENV_VARS_SCRIPT

    config.vm.provision "shell", inline: $set_environment_variables, run: "always"

    config.vm.synced_folder "../../../", "/home/elastio/elastio-snap", type: "rsync",
      rsync__args: ["-rLkz", "--delete", "--filter=:- .gitignore"], rsync__exclude: [".vagrant/"]

end
